---
title: "Text Data Retrieval"
author: "Nisaar Hussain"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the packages

```{r}
rm(list=ls())

library(tidyverse)
library(rvest) # This is one package that handles webpages retrieval and parsing
library(xml2) # This is another package that handles webpages retrieval and parsing

dir.create("Lecture 10/data_1") # Create a new folder
```

## Retrieve CE's last article

```{r}
# Use the download.file function
# Directly download files through URL and specify download location
download.file(
  url = "https://www.ceo.gov.hk/archive/5-term/eng/pdf/article20220530.pdf",
  destfile = "Lecture 10/2_Web_Scraping/data_1/20220530.pdf")
```

## Retrieve CE's last speech
```{r}
# downloading text of the webpages only, excludes the images 
doc_html <- read_html("https://www.info.gov.hk/gia/general/202206/21/P2022062100598.htm")
write_html(doc_html, "Lecture 10/2_Web_Scraping/data_1/20220621.htm")
```

## Remarks

-   _html function is available on both rvest and xml2 packages
-   e_html function is only available on xml2 package